### ISSUE TITLE
Bitte folgendes Fixen/Ändern

### ISSUE THREAD

**Issue by Apollon77** [Eisbaeeer/ioBroker.alpha2#1]
* WARNING: No news entry for current version exists in io-package.json, no rollback in Admin possible!
* WARNING: titleLang is not existing in io-package.json. Please add

* Bitte admin/index.html entfernen wenn Admin2 support nicht vorhanden ist
* io-package bitte "common.restartAdapters" raus wenn kein widget drin ist
* io-package bitte "common.license " dazu mit der Lizenzangabe
* io-package in native bitte alle Parameter mit den Default-Werten rein nehmen

* Im Code gehen alle Posts an eine statische IP?? Soll das so sein?
* Bitte beim anlegen von Objekten nicht setObject sondern setObjectNotExists nutzen ODER statische Objekte in der io-package unter "instanceObjects" anlegen
* Objekte Role "EZR" ist keine erlaubte ioBroker Rollenangabe. Siehe hier: https://github.com/ioBroker/ioBroker/blob/master/doc/STATE_ROLES.md Bitte ROllen der Datenpunkte korrekt setzen

Danke

**Comment by Eisbaeeer** [comment]
In Arbeit. Zum Glück haben wir dich ;-)

**Comment by Eisbaeeer** [comment]
fixed issue #1 with verison 0.0.2

**Comment by Apollon77** [comment]
thx!
