### ISSUE TITLE
T_TARGET not working

### ISSUE THREAD

**Issue by Grantlhaua** [Eisbaeeer/ioBroker.alpha2#17]
Hello, 

when I set T_Target in Iobroker, the temperature will be overided by the next Update.

For Example:

When the target temperature is 21° and I override it by Iobroker with 25°, the Adapter will override it again with 21° by next actualisation.

**Comment by Eisbaeeer** [comment]
Hi. Do you using a manual Room thermostate or is it a digital one with display in this zone?

**Comment by Grantlhaua** [comment]
Hi, I'm using Raumthermostat Alpha 2 Bus 24V LCD RDB 74202 and the 24 Basisstation with 8 heat areas. Labeled by Kermi. (Raumbediengerät Bus D1 and Kermi Schaltaktor 24V)

**Comment by Eisbaeeer** [comment]
Komisch. Das sollte mit digitalen schon klappen. Habe auch eine Alpha2 mit LCD und Bus verbaut. Ich teste das bei Gelegenheit.

**Comment by Grantlhaua** [comment]
also ich schreib einfach die Temperatur in den Objekten per Hand in T_Target und nach ein paar Sekunden bei der nächsten Aktualisierung durch den Adapter steht wieder die vorherige Temperatur drin. Vielleicht mach ich auch was falsch oder hab was übersehen? Muss ich vielleicht auf der Weboberfläche von Möllenhoff den Fernzugriff freigeben?

**Comment by Eisbaeeer** [comment]
Also ich habe eben nochmal im code nachgesehen. Sollte so gehen. Setzen der Variable T_Target. Über die API wird dann die Zieltemperatur gesetzt. Kannst du mal bitte testen, ob du im Manager die Temperatur für diesen Thermostaten setzen kannst? Also auf der Alpha2 Weboberfläche?

**Comment by Grantlhaua** [comment]
Was ist denn das ack bit? Ich habe jetzt Testweise einfach nur die Temperatur in den Objekten "per Hand" bei T_Target geändert. 

Ich sehe grad bei der Station im Keller kann ichs ändern, bei der im EG nicht. Die hab ich jetzt gerade auch irgendwie zum abstürzen gebracht...

**Comment by Grantlhaua** [comment]
Jetzt geht der im EG gar nimma. Ich denke ich muss den evtl mal auf Werkseinstellungen zurücksetzen....

**Comment by Eisbaeeer** [comment]
In den Objekten in iobroker gibt es einen Haken und eine Checkbox. Die checkbox darf nicht angehakt sein und zum Setzen des Wertes den Haken anklicken. Oder mal über ein Input Widget in VIS versuchen.

**Comment by Grantlhaua** [comment]
Ich denke es liegt an der Basisstation, da die Im Keller die Werte nimmt und die im EG nicht. Die im OG geht aber auch schon wieder nicht. Zuverlässig ist das System von Möhlenhoff leider nicht finde ich. 

Ich setze die 2 mal zurück und melde mich dann nochmal zurück

**Comment by Grantlhaua** [comment]
![Screenshot_20210219_150907](https://user-images.githubusercontent.com/62055414/108514677-7363aa00-72c4-11eb-9e73-a8a8812b3a25.jpg)

So nimmt er mir die Änderung im EG nicht. Im Keller funktionierts

**Comment by Eisbaeeer** [comment]
Hast du mal geschaut, ob es eine neuere Firmware für die Alpha gibt? Ich hatte das anfangs auch, dass die sich komplett verabschiedet hat, wenn ich mit XML per API drauf logegangen bin.

**Comment by Grantlhaua** [comment]
Kann ich die im Browser updaten oder nur per SD Karte?

**Comment by Eisbaeeer** [comment]
Da bin ich überfragt. Soweit ich weiß über SD Karte.

**Comment by orhan77971** [comment]
Ich habe ein ähnliches Problem. Bei mir lassen sich 3 von 4 Zonen problemlos bedienen. Nur bei der 4 Zone lässt sich der Wert nicht übernehmen und switcht bei der polling time period zurück. Möglicherweise liegt es am Funk-Thermostat?

Zur Zeit gibt es auch sehr viele warn-meldungen im LOG  - (5684) State "alpha2.0.HEATCTRL.11.INUSE" has no existing object, this might lead to an error in future versions. Wie kann man diese Warnungen abstellen?

**Comment by Eisbaeeer** [comment]
Hi. Ich denke diese Meldung hat damit zu tun, dass er die Zone 11 nicht unterstützt. Welche Alpha nutzt du? Sind das 12 Zonen?

**Comment by orhan77971** [comment]
Ja ich habe 12 Zonen.

**Comment by Eisbaeeer** [comment]
> Ja ich habe 12 Zonen. (war die billigste version)
Ich hatte damals leider keine Alpha mit 12 Zonen zur Verfügung gestellt bekommen. Zur Entwicklung habe ich eine 8-Zonen Alpha2 bekommen. Deshalb auch der Hinweis, dass nur bis 8 Zonen unterstützt werden. Das sollte aber einfach durch "copy-paste" auf die 12 Zonen erweitert werden können. Leider kann ich das nich testen. Ich hab keine Alpha mehr zur Verfügung.

**Comment by orhan77971** [comment]
Okay danke für die schnelle Antwort. Ich würde das gerne selbst beheben. Wo in welcher Datei kann ich das machen? Gibt es eine Art Tutorial?

**Comment by orhan77971** [comment]
Die Stelle / Datei wo man die Einträge macht würde mir auch reichen. Ich würde dann das Ergebnis auch zur Verfügung stellen.

**Comment by Eisbaeeer** [comment]
> Die Stelle / Datei wo man die Einträge macht würde mir auch reichen. Ich würde dann das Ergebnis auch zur Verfügung stellen.

Hi. Du müsstest den Code in der main.js und io-package.json anpassen. In der io-package.json sind die Objekte, welche du zusätzlich anlegst, hinzuzufügen. Du kannst dich an den vorhandenen orientieren. in der main.js sind die Funktionen enthalten, wie die XML-API bedient wird. Auch da kannst du mal bei den vorhandenen Zonen abschauen. Es ist mehr oder weniger ein Kopieren und anpassen des vorhandenen Codes.
Leider kann ich im Moment weder die 8-Kanal, noch eine 12-Kanal testen, da ich nur eine Leihstellung von Möhlenhoff hatte und diese schon längst wieder zurückgesendet habe.
Gruß Lars

**Comment by orhan77971** [comment]
Hi. Erstmal danke für die vielen Infos. 
Ich habe nun den Code in den angegebenen Dateien angepasst / erweitert im Ordner opt/iobroker/node_modules/iobroker.alpha2

Auch nach dem restart von iobroker gibt es bisher keine neuen Objekte. War das der richtige Pfad? Muss man diese dateien neu laden? Wenn ja, wie?

Danke schonmal für die Mühe

**Comment by Eisbaeeer** [comment]
> Auch nach dem restart von iobroker gibt es bisher keine neuen Objekte. War das der richtige Pfad? Muss man diese dateien neu laden? Wenn ja, wie?

Du musst die Änderung entweder direkt in iobroker im adapterverzeichnis anpassen und den Adapter dann neu starten oder besser, die Änderung in Github machen und den Adapter von dort neu installieren. Dann werden auch die Objekte angelegt,
Gruß Eisbaeeer

**Comment by Grantlhaua** [comment]
> Da bin ich überfragt. Soweit ich weiß über SD Karte.

Guten Morgen, 

ich hab vor einiger Zeit das Upate bei Möhlenhoff angefragt und habs heute endlich drauf gespielt. Ich werde jetzt den Adapter testen und dann nochmal rückmeldung geben :)
