### ISSUE TITLE
Warning!  alpha2.0.HEATCTRL.11.HEATCTRL_STATE

### ISSUE THREAD

**Issue by AcidSubway** [Eisbaeeer/ioBroker.alpha2#18]
Hallo Eisbaeeer,

ich hab das Problem das mir ioBroker ständig das meldet:

`

alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.11.HEATCTRL_STATE" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.11.ACTOR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.11.HEATAREA_NR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.11.INUSE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.10.HEATCTRL_STATE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.10.ACTOR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.493 | warn | (6133) State "alpha2.0.HEATCTRL.10.HEATAREA_NR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.492 | warn | (6133) State "alpha2.0.HEATCTRL.10.INUSE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.492 | warn | (6133) State "alpha2.0.HEATCTRL.9.HEATCTRL_STATE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.492 | warn | (6133) State "alpha2.0.HEATCTRL.9.ACTOR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.492 | warn | (6133) State "alpha2.0.HEATCTRL.9.HEATAREA_NR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.492 | warn | (6133) State "alpha2.0.HEATCTRL.9.INUSE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.492 | warn | (6133) State "alpha2.0.HEATCTRL.8.HEATCTRL_STATE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.491 | warn | (6133) State "alpha2.0.HEATCTRL.8.ACTOR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.491 | warn | (6133) State "alpha2.0.HEATCTRL.8.HEATAREA_NR" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.491 | warn | (6133) State "alpha2.0.HEATCTRL.8.INUSE" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.454 | warn | (6133) State "alpha2.0.PROGRAM.16.16.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.454 | warn | (6133) State "alpha2.0.PROGRAM.16.16.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.454 | warn | (6133) State "alpha2.0.PROGRAM.15.15.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.454 | warn | (6133) State "alpha2.0.PROGRAM.15.15.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.454 | warn | (6133) State "alpha2.0.PROGRAM.14.14.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.454 | warn | (6133) State "alpha2.0.PROGRAM.14.14.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.13.13.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.13.13.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.12.12.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.12.12.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.11.11.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.11.11.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.453 | warn | (6133) State "alpha2.0.PROGRAM.10.10.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.10.10.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.9.9.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.9.9.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.8.8.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.8.8.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.7.7.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.452 | warn | (6133) State "alpha2.0.PROGRAM.7.7.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.451 | warn | (6133) State "alpha2.0.PROGRAM.6.6.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.451 | warn | (6133) State "alpha2.0.PROGRAM.6.6.START" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.451 | warn | (6133) State "alpha2.0.PROGRAM.5.5.END" has no existing object, this might lead to an error in future versions
alpha2.0 | 2021-03-08 19:37:05.451 | warn | (6133) State "alpha2.0.PROGRAM.5.5.START" has no existing object, this might lead to an error in future versions

`

Kannst du damit was anfangen?
Das kam nach einem Update von ioBroker.

MfG

AcidSubway

**Comment by Eisbaeeer** [comment]
Ich vermute, dass die Objekt Struktur nach dem Update nicht mehr gültig ist. Ist derzeit aber nur ein Hinweis. Schau mal nach, ob diese Objekte angelegt wurden.
Gruß Lars

**Comment by MrFisch** [comment]
Ist bei mir exakt das gleiche Problem. Die Objekte wurden nicht angelegt. Hast du noch eine idee?

**Comment by MrFisch** [comment]
Ich konnte für meinen Fall das Problem lösen. Ich habe die Version 1.0.1 als Grundlage genommen. Es wurden in der main.js über die Schleifenzähler auf Datenpunkte geschrieben, die aber über die io-package.json nicht angelegt worden sind. Hab bei den Datenpunkten eine einfache "if" Bedingung eingefügt, die bei den "Programm" Datenpunkten nur bis max. 4 zählt und nicht wie bisher bis 16. Außerdem wurde in der "io-package.json" als Unit statt °C ein zusätzliches "Sonderzeichen" eingefügt... das ist / war aber nur ein kleiner Schönheitsfehler.

**Comment by manylomy** [comment]
Hallo zusammen,
auch bei mir erscheint die Meldung:


State "alpha2.0.HEATCTRL.11.HEATCTRL_STATE" has no existing object, this might lead to an error in future versions

Ich habe die Message von MrFisch zwar gelesen aber nicht verstanden. Wo oder welche Version 1.0.1 ist gemeint. Bei iobroker finde ich für den Adapter nur die 1.0.0. 
Selbst wenn ich die finde, ich weiß nicht, ob ich die beschriebene Ändeung einbauen kann, keine Erfahrung in Treiberprogrammierung etc.
Wer kann mir da "auf die Sprünge" helfen?

Vielen Dank, Manylomy

**Comment by noob-pi** [comment]
Habe genau das gleiche Problem. 
Schließe mich @manylomy an ich versteh leider auch nicht so ganz was @MrFisch genau meinte. 

@MrFisch Könntest du die 1.0.1 Version anbieten? (Download)
Oder vielleicht eine bessere oder genau Vorgehensweise für die nicht Programmier Profis schreiben? ;-)

@Eisbaeeer Wäre es möglich das du die Version als Update einfügen könntest?

Vielen Dank euch

Grüße

**Comment by AcidSubway** [comment]
@Eisbaeeer wäre ein Update möglich, weil ich komm da auch nicht mit was das umstellen angeht?

**Comment by AcidSubway** [comment]
@Eisbaeeer 
ich schließe mich dem @noob-pi  an, nicht jeder versteht das immer :) könntest du bitte ein update machen?

**Comment by MrFisch** [comment]
Gibt es eine Möglichkeit meine Scripts hochzuladen? Das macht es vermutlich am einfachsten

**Comment by luft-post** [comment]
@MrFisch: wollen wir einfach im iobroker Forum einen Post zu diesen Workaround aufmachen?
Da könnten wir auch Skripte hochladen und würden bestimmt noch mehr betroffene Nutzer erreichen.

gruß
Matthias

**Comment by Eisbaeeer** [comment]
Hallo zusammen
Ich habe mich heute hingesetzt. Der Adapter sollte wieder funktionieren. Ich konnte jetzt eine Alpha2 auftreiben und bei mir hat soweit alles wieder funktioniert.
Ihr müsst derzeit den Adapter von Hand installieren, bis er in das Repo einfließt. Folgt bitte folgenden Schritten:
![alpha-01](https://user-images.githubusercontent.com/4928271/140043564-c5570fb5-13bb-4350-b09d-53392baa6b8c.png)

![alpha-02](https://user-images.githubusercontent.com/4928271/140043627-bd453a32-a8fa-4666-aa1f-94e8a72b322c.png)

![alpha-03](https://user-images.githubusercontent.com/4928271/140043642-328c9513-313d-4f9f-a123-328482ae8488.png)

![alpha-04](https://user-images.githubusercontent.com/4928271/140043677-d6e47471-00da-4600-aa4e-31b6c5b47202.png)

![alpha-05](https://user-images.githubusercontent.com/4928271/140043710-bef4ee98-40c8-42c6-a2ce-20846acabed6.png)

![alpha-06](https://user-images.githubusercontent.com/4928271/140043724-3f9b7596-dea0-456c-b837-b282d778b521.png)

**Comment by HerrBier** [comment]
Hat bei mir leider nichts bewirkt :-(

![grafik](https://user-images.githubusercontent.com/77205902/140050236-8912a788-2d63-41d1-bd2d-16107a793461.png)

**Comment by Eisbaeeer** [comment]
@HerrBier  Bitte nochmal die aktuelle Version installieren. Habe inzwischen die Version 1.0.2 online. Danke.

**Comment by HerrBier** [comment]
Hab grad gesehen, die neue Version war da :-) 
Die Warnungen sind weg. Dankeschön 👍 

Jetzt weiß ich nicht, ob die Log-Einträge durchs Update kommen: 
![grafik](https://user-images.githubusercontent.com/77205902/140230768-ed94703a-54ed-4192-aecb-c35e1c5f4af3.png)

**Comment by MrFisch** [comment]
Super Arbeit! Vielen Dank. Das macht es auf alle Fälle einfacher wenn man das System neu aufsetzt. Der letzte Post mit den fehlerhaften Typ lässt sich manuell auch leicht lösen, wenn man bei den Objekten den Typ „Mixed“ bzw „gemischt“ auswählt. Der beste Weg wäre natürlich das Script für die Generierung der datenpunkte anzupassen.

**Comment by Eisbaeeer** [comment]
@HerrBier Ist gefixt. Die Warnung sollte jetzt nicht mehr erscheinen.

**Comment by luft-post** [comment]
@Eisbaeeer 
Vielen vielen Dank, hab geupdatet und die Warnungen sind weg und es scheint alles zu Funktionieren.
Nochmal vielen Dank das du dich dessen angenommen hast.

Gruß
Matthias

**Comment by HerrBier** [comment]
Sieht gut aus :-)
Vielen, vielen Dank für die Mühe. Das wird viel mehr Leuten helfen, als denen, die sich hier melden.

**Comment by AcidSubway** [comment]
VIELEN DANK!  Danke für deine Zeit :)
