### ISSUE TITLE
Fehler XML-Parsen: Error: Unexpected close tag

### ISSUE THREAD

**Issue by mcmuller** [Eisbaeeer/ioBroker.alpha2#5]
I frequently get the following errors, though the adapter is working as expected. You may have a look....
`
alpha2.0 | 2018-09-09 13:05:49.937 | info | Char: >
alpha2.0 | 2018-09-09 13:05:49.937 | info | Column: 11
alpha2.0 | 2018-09-09 13:05:49.937 | info | Line: 397
alpha2.0 | 2018-09-09 13:05:49.937 | info | Fehler XML-Parsen: Error: Unexpected close tag
alpha2.0 | 2018-09-09 13:03:49.829 | info | Char: >
alpha2.0 | 2018-09-09 13:03:49.829 | info | Column: 43
alpha2.0 | 2018-09-09 13:03:49.829 | info | Line: 107
alpha2.0 | 2018-09-09 13:03:49.829 | info | Fehler XML-Parsen: Error: Unexpected close tag
alpha2.0 | 2018-09-09 13:03:19.831 | info | Char: >
alpha2.0 | 2018-09-09 13:03:19.831 | info | Column: 68
alpha2.0 | 2018-09-09 13:03:19.831 | info | Line: 50
alpha2.0 | 2018-09-09 13:03:19.831 | info | Fehler XML-Parsen: Error: Unexpected close tag
alpha2.0 | 2018-09-09 12:53:49.683 | info | Char: >
alpha2.0 | 2018-09-09 12:53:49.683 | info | Column: 51
alpha2.0 | 2018-09-09 12:53:49.683 | info | Line: 249
alpha2.0 | 2018-09-09 12:53:49.683 | info | Fehler XML-Parsen: Error: Unexpected close tag
alpha2.0 | 2018-09-09 12:06:18.885 | info | Char: >
alpha2.0 | 2018-09-09 12:06:18.885 | info | Column: 68
alpha2.0 | 2018-09-09 12:06:18.885 | info | Line: 50
alpha2.0 | 2018-09-09 12:06:18.885 | info | Fehler XML-Parsen: Error: Unexpected close tag

`
Greetings,
Gregor

**Comment by Eisbaeeer** [comment]
Will test after receive the next test unit.

**Comment by mcmuller** [comment]
...gone after last admin upgrade.
