### ISSUE TITLE
No Device Datas

### ISSUE THREAD

**Issue by Klutez** [Eisbaeeer/ioBroker.alpha2#6]
After adapter configuration, the values appears for the device settings, but heatareas are leaving blank. I can manually set the value for T_HEAT_DAY and the the value is correcly written to the EZ-Manager.

Thanks for this adapter!!!

Greez, Markus

**Comment by Eisbaeeer** [comment]
I will check that, if I get a alpha2 controller again. It takes some weeks, but I ordered 2 of them.

**Comment by Eisbaeeer** [comment]
Hey Markus
Fixed that in the new version. Sorry for long delay, but I got an Alpha2 Controller last weeks for develop.
